### ISSUE TITLE
Not found any quantized model which meet accuracy goal

### ISSUE THREAD

**Issue by sharmi1206** [intel/neural-compressor#956] opened 2023-06-09 06:04 UTC
With neural compressor version 2.2 , seeing this issue.

Code is listed below:

from neural_compressor.config import PostTrainingQuantConfig
from neural_compressor.data import DataLoader
from neural_compressor.data import Datasets
from neural_compressor.quantization import fit
from neural_compressor import Metric
dataset = Datasets('tensorflow')['dummy'](shape=(1, 224, 224, 3))
dataloader = DataLoader(framework='tensorflow', dataset=dataset)

config = PostTrainingQuantConfig()

top1 = Metric(name="topk", k=1)
# Just call fit to do quantization.
q_model = fit(model="mobilenet_v1_1.0_224_frozen.pb",
              conf=config,
              calib_dataloader=dataloader,
              eval_dataloader=dataloader,
              eval_metric=top1)

Output from code:

2023-06-09 05:59:04 [INFO] Pass StripUnusedNodesOptimizer elapsed time: 20.03 ms
2023-06-09 05:59:04 [INFO] Pass RemoveTrainingNodesOptimizer elapsed time: 4.37 ms
2023-06-09 05:59:04 [INFO] Pass SplitSharedInputOptimizer elapsed time: 2.02 ms
2023-06-09 05:59:04 [INFO] Pass GraphFoldConstantOptimizer elapsed time: 2.0 ms
2023-06-09 05:59:04 [INFO] Pass FuseDecomposedBNOptimizer elapsed time: 4.66 ms
2023-06-09 05:59:04 [INFO] Pass FuseColumnWiseMulOptimizer elapsed time: 3.28 ms
2023-06-09 05:59:04 [INFO] Pass StripUnusedNodesOptimizer elapsed time: 6.6 ms
2023-06-09 05:59:04 [INFO] Pass GraphCseOptimizer elapsed time: 3.37 ms
2023-06-09 05:59:04 [INFO] Pass FoldBatchNormNodesOptimizer elapsed time: 2.08 ms
2023-06-09 05:59:04 [INFO] Pass RenameBatchNormOptimizer elapsed time: 2.8 ms
2023-06-09 05:59:04 [INFO] Pass ConvertLeakyReluOptimizer elapsed time: 2.98 ms
2023-06-09 05:59:04 [INFO] Pass ConvertAddToBiasAddOptimizer elapsed time: 2.13 ms
2023-06-09 05:59:04 [INFO] Pass FuseTransposeReshapeOptimizer elapsed time: 4.81 ms
2023-06-09 05:59:04 [INFO] Pass FuseConvWithMathOptimizer elapsed time: 6.03 ms
2023-06-09 05:59:04 [INFO] Pass ExpandDimsOptimizer elapsed time: 3.34 ms
2023-06-09 05:59:04 [INFO] Pass FetchWeightFromReshapeOptimizer elapsed time: 3.3 ms
2023-06-09 05:59:04 [INFO] Pass MoveSqueezeAfterReluOptimizer elapsed time: 3.14 ms
2023-06-09 05:59:04 [WARNING] Found possible input node names: ['input'], output node names: ['MobilenetV1/Predictions/Reshape_1'].
2023-06-09 05:59:04 [INFO] Pass InjectDummyBiasAddOptimizer elapsed time: 8.76 ms
2023-06-09 05:59:05 [WARNING] All replaced equivalent node types are {}
2023-06-09 05:59:05 [INFO] Pass StripEquivalentNodesOptimizer elapsed time: 13.99 ms
2023-06-09 05:59:05 [INFO] Pass Pre Optimization elapsed time: 692.32 ms
2023-06-09 05:59:05 [INFO] Get FP32 model baseline.
2023-06-09 05:59:05 [INFO] Start to evaluate the TensorFlow model.
2023-06-09 05:59:06 [INFO] Model inference elapsed time: 741.09 ms
2023-06-09 05:59:06 [INFO] Save tuning history to /content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/nc_workspace/2023-06-09_05-55-17/./history.snapshot.
2023-06-09 05:59:06 [INFO] FP32 baseline is: [Accuracy: 0.0000, Duration (seconds): 0.7471]
2023-06-09 05:59:06 [INFO] Quantize the model with default config.
2023-06-09 05:59:23 [WARNING] Please note the 2.12.0 version of TensorFlow is not fully verified! Suggest to use the versions between 1.14.0 and 2.11.0 if meet problem.
2023-06-09 05:59:23 [WARNING] Found possible input node names: ['input'], output node names: ['MobilenetV1/Predictions/Reshape_1'].
2023-06-09 05:59:23 [WARNING] Found possible input node names: ['input'], output node names: ['MobilenetV1/Predictions/Reshape_1'].
2023-06-09 05:59:23 [WARNING] Found possible input node names: ['input'], output node names: ['MobilenetV1/Predictions/Reshape_1'].
2023-06-09 05:59:24 [INFO] Pass Quantization elapsed time: 384.57 ms
2023-06-09 05:59:24 [ERROR] Fail to quantize graph due to fileno.
2023-06-09 05:59:24 [WARNING] Fail to forward with batch size=1, set to 1 now.
2023-06-09 05:59:24 [WARNING] Please note the 2.12.0 version of TensorFlow is not fully verified! Suggest to use the versions between 1.14.0 and 2.11.0 if meet problem.
2023-06-09 05:59:24 [WARNING] Found possible input node names: ['input'], output node names: ['MobilenetV1/Predictions/Reshape_1'].
2023-06-09 05:59:25 [WARNING] Found possible input node names: ['input'], output node names: ['MobilenetV1/Predictions/Reshape_1'].
2023-06-09 05:59:25 [WARNING] Found possible input node names: ['input'], output node names: ['MobilenetV1/Predictions/Reshape_1'].
2023-06-09 05:59:25 [INFO] Pass Quantization elapsed time: 570.1 ms
2023-06-09 05:59:26 [ERROR] Fail to quantize graph due to fileno.
2023-06-09 05:59:26 [ERROR] Unexpected exception UnsupportedOperation('fileno') happened during tuning.
Traceback (most recent call last):
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/adaptor/tensorflow.py", line 584, in quantize
    use_bf16=self.use_bf16).convert()
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/adaptor/tf_utils/graph_converter.py", line 366, in convert
    model = self.quantize()
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/adaptor/tf_utils/graph_converter.py", line 532, in quantize
    with CaptureOutputToFile(tmp_dump_file):
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/utils/utility.py", line 442, in __init__
    self.orig_stream_fileno = stream.fileno()
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/quantization.py", line 215, in fit
    strategy.traverse()
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/strategy/auto.py", line 108, in traverse
    super().traverse()
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/strategy/strategy.py", line 420, in traverse
    q_model = self.adaptor.quantize(copy.deepcopy(tune_cfg), self.model, self.calib_dataloader, self.q_func)
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/utils/utility.py", line 303, in fi
    res = func(*args, **kwargs)
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/adaptor/tensorflow.py", line 603, in quantize
    use_bf16=self.use_bf16).convert()
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/adaptor/tf_utils/graph_converter.py", line 366, in convert
    model = self.quantize()
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-**master/neural_compressor/adaptor/tf_utils/graph_converter.py", line 532, in quantize
    with CaptureOutputToFile(tmp_dump_file):
  File "/content/drive/My Drive/Colab Notebooks/model_quantization/neural-compressor-master/neural_compressor/utils/utility.py", line 442, in __init__
    self.orig_stream_fileno = stream.fileno()
io.UnsupportedOperation: fileno
2023-06-09 05:59:27 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.**

**Comment by lvliang-intel** [comment] 2023-06-11 09:38
Hi @sharmi1206,
Thank you for bringing up this issue. The root cause of the problem lies in the way Jupyter Notebooks capture system input and output. However, Intel Neural Compressor requires access to the standard input and output for calibration purposes. To address this issue, you will need to set up a Conda environment for testing.

**Comment by chensuyue** [comment] 2023-06-27 10:16
@sharmi1206 Does this suggestion resolve your issue? Could we close this ticket?

**Comment by chensuyue** [comment] 2023-09-19 01:56
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.

**Closed by chensuyue** 2023-09-19 01:56 UTC

**Comment by mattam301** [comment] 2023-09-24 03:06
Hello there, i encounter the same issue but have no idea how to proceed, how have you dealt with this?
