### ISSUE TITLE
Request some update for ipex quantization

### ISSUE THREAD

**Issue by rnwang04** [intel/neural-compressor#124] opened 2022-10-31 14:29 UTC
Hi team, when I use inc + ipex quantization on unet, I meet three bugs and I have fixed part of them locally.
Here raise this issue is hoping you can fix these these bugs at inc source code.

Torch version: 1.12.1
IPEX version: 1.12.100
inc version: 1.14.1

1. about get_input_sample
https://github.com/intel/neural-compressor/blob/5cc5dab450dfdc495537b41224be02c06432355a/neural_compressor/adaptor/pytorch.py#L72-L75
here my input looks like (latent_tensor, length, encoding)
and I just need these three elements to model(*input_sample).
I modify this to :
```
if isinstance(example_inputs, list) or isinstance(example_inputs, tuple):
     return example_inputs
```
then it works.

2. about bf16 ops
https://github.com/intel/neural-compressor/blob/5cc5dab450dfdc495537b41224be02c06432355a/neural_compressor/adaptor/pytorch.py#L3452-L3454
here it will report bug as 'bf16' not in self.cur_config['ops'].keys().
I fix it to:
```
if precision in list(self.cur_config['ops'].keys()):
     return self.cur_config['ops'][precision]
else:
     return []
```
then it works.

3.  about target space
https://github.com/intel/neural-compressor/blob/5cc5dab450dfdc495537b41224be02c06432355a/neural_compressor/strategy/bayesian.py#L228
I also meet error when running this line, the pbounds and error message looks like this:
```
{((' ', 'q_op_infos', '0'),): (0, 4), ((' ', 'q_op_infos', '1'),): (0, 4), (('time_embedding', 'q_op_infos', '0'),): (0, 4), (('time_embedding', 'q_op_infos', '1'),): (0, 4), (('down_blocks:0:attentions:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('down_blocks:0:attentions:0:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('down_blocks:0:attentions:1:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:0:resnets:0', 'q_op_infos', '1'),): (0, 4), (('down_blocks:0:resnets:1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:0:downsamplers:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('down_blocks:1:attentions:0:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('down_blocks:1:attentions:1:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:1:resnets:0', 'q_op_infos', '1'),): (0, 4), (('down_blocks:1:resnets:0', 'q_op_infos', '4'),): (0, 4), (('down_blocks:1:resnets:1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:1:downsamplers:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('down_blocks:2:attentions:0:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('down_blocks:2:attentions:1:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('down_blocks:2:resnets:0', 'q_op_infos', '1'),): (0, 4), (('down_blocks:2:resnets:0', 'q_op_infos', '4'),): (0, 4), (('down_blocks:2:resnets:1', 'q_op_infos', '1'),): (0, 4), (('down_blocks:2:downsamplers:0', 'q_op_infos', '0'),): (0, 4), (('down_blocks:3:resnets:0', 'q_op_infos', '1'),): (0, 4), (('down_blocks:3:resnets:1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:0:resnets:0', 'q_op_infos', '1'),): (0, 4), (('up_blocks:0:resnets:0', 'q_op_infos', '4'),): (0, 4), (('up_blocks:0:resnets:1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:0:resnets:1', 'q_op_infos', '4'),): (0, 4), (('up_blocks:0:resnets:2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:0:resnets:2', 'q_op_infos', '4'),): (0, 4), (('up_blocks:0:upsamplers:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:1:attentions:0:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:1:attentions:1:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:1:attentions:2:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:1:resnets:0', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:resnets:0', 'q_op_infos', '4'),): (0, 4), (('up_blocks:1:resnets:1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:resnets:1', 'q_op_infos', '4'),): (0, 4), (('up_blocks:1:resnets:2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:1:resnets:2', 'q_op_infos', '4'),): (0, 4), (('up_blocks:1:upsamplers:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:2:attentions:0:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:2:attentions:1:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:2:attentions:2:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:2:resnets:0', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:resnets:0', 'q_op_infos', '4'),): (0, 4), (('up_blocks:2:resnets:1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:resnets:1', 'q_op_infos', '4'),): (0, 4), (('up_blocks:2:resnets:2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:2:resnets:2', 'q_op_infos', '4'),): (0, 4), (('up_blocks:2:upsamplers:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:3:attentions:0:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:3:attentions:1:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('up_blocks:3:attentions:2:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('up_blocks:3:resnets:0', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:resnets:0', 'q_op_infos', '4'),): (0, 4), (('up_blocks:3:resnets:1', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:resnets:1', 'q_op_infos', '4'),): (0, 4), (('up_blocks:3:resnets:2', 'q_op_infos', '1'),): (0, 4), (('up_blocks:3:resnets:2', 'q_op_infos', '4'),): (0, 4), (('mid_block:attentions:0', 'q_op_infos', '0'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '0'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '1'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:attn1', 'q_op_infos', '2'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:attn1:to_out', 'q_op_infos', '0'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:ff:net:0', 'q_op_infos', '0'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '0'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '1'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:attn2', 'q_op_infos', '2'),): (0, 4), (('mid_block:attentions:0:transformer_blocks:0:attn2:to_out', 'q_op_infos', '0'),): (0, 4), (('mid_block:resnets:0', 'q_op_infos', '1'),): (0, 4), (('mid_block:resnets:1', 'q_op_infos', '1'),): (0, 4), 'calib_sampling_size': (0, 1)}
2022-10-31 18:15:15 [ERROR] Unexpected exception TypeError("'<' not supported between instances of 'str' and 'tuple'") happened during tuning.
Traceback (most recent call last):
File "/opt/anaconda3/envs/nano/lib/python3.7/site-packages/neural_compressor/experimental/quantization.py", line 163, in execute
	self.strategy.traverse()
File "/opt/anaconda3/envs/nano/lib/python3.7/site-packages/neural_compressor/strategy/strategy.py", line 219, in traverse
	for op_tuning_cfg in self.next_tune_cfg():
File "/opt/anaconda3/envs/nano/lib/python3.7/site-packages/neural_compressor/strategy/bayesian.py", line 135, in next_tune_cfg
	pbounds=pbounds, random_seed=self.cfg.tuning.random_seed)
File "/opt/anaconda3/envs/nano/lib/python3.7/site-packages/neural_compressor/strategy/bayesian.py", line 397, in __init__
	self._space = TargetSpace(pbounds, random_seed)
File "/opt/anaconda3/envs/nano/lib/python3.7/site-packages/neural_compressor/strategy/bayesian.py", line 229, in __init__
	self._keys = sorted(pbounds)
TypeError: '<' not supported between instances of 'str' and 'tuple'
```
Actually I don't understand this bug and don't know how to fix this. 
But after I reduce inc version to 1.13.1, it works.

I wonder if you can fix these problems in inc. Thanks a lot.

**Comment by chensuyue** [comment] 2022-11-01 08:04
Hi, thanks for raising the issue.    
Issue 1 and 2 has been resolved in INC v1.14.2, and Issue3 has been reported to our developer, we will let you know when we find the root cause.

**Comment by yiliu30** [comment] 2022-11-02 05:07
Hi @rnwang04, thanks for raising this issue. Could you please provide the model and code to help reproduce issue 3? If you are using the example from INC, could you please provide the example link?

**Comment by rnwang04** [comment] 2022-11-03 09:11
@chensuyue @yiliu30 Have shared code to @yiliu30 , and he has fixed this bug. Really thanks for your so quick response and bug fix !!

**Closed** 2022-11-07 06:13 UTC

**Comment by rnwang04** [comment] 2022-11-09 13:41
@chensuyue  one question here, after I install inc==1.14.2, I still meet the first error, and I find the code of get_input_sample don't change.
![image](https://user-images.githubusercontent.com/105281011/200845161-94bec8db-0713-4319-ab5e-e24fda6beae3.png)
